#ifndef __RTE_COMPONENTS_H__
#define __RTE_COMPONENTS_H__

#define RTE_DEVICE_STDPERIPH_EXTI
#define RTE_DEVICE_STDPERIPH_GPIO
#define RTE_DEVICE_STDPERIPH_I2C
#define RTE_DEVICE_STDPERIPH_RCC
#define RTE_DEVICE_STDPERIPH_USART
#define RTE_DEVICE_STDPERIPH_FRAMEWORK

#endif
